version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postnews
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network
            
  app:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    container_name: next-app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_started
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    restart: always
    volumes:
      - ./app:/app/app
    networks:
      - app-network

volumes:
    postgres_data:
      driver: local

networks:
  app-network:
    driver: bridge
