version: '3.8'

services:
  # Сервис для PostgreSQL
  db:
    image: postgres:14
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postnews
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  # Сервис для Next.js
  next:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    environment:
      DATABASE_URL: postgresql://postgres:12345@db:5432/postnews?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["npm", "run", "dev"]
  
volumes:
  postgres_data:
